version: "3"
services:
  app:
    container_name: php-rbc
    build: ./docker/php
    working_dir: /var/www/api
    restart: always 
    volumes:
      - ./api:/var/www/api
    depends_on:
      - mysql

  nginx:
    container_name: nginx-rbc
    image: nginx:latest
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app

  mysql:
    container_name: mysql-rbc
    image: mysql:8.0
    restart: always
    volumes:
      - ./tmp/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=currency
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=rbc
      - MYSQL_PASSWORD=123
    ports:
      - 3307:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci